import { StyleSheet } from 'react-native';
import Colors from '@/constants/colors';

// Estilos compartidos de todas las pantallas de auditoria
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  scrollView: {
    flex: 1,
  },
  tabsScrollView: {
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    height: 40,
  },
  tabsRow: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    paddingHorizontal: 8,
    paddingVertical: 6,
    justifyContent: 'space-around',
  },
  tabsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  tabButton: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5f5f5',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    minWidth: 50,
  },
  tabButtonActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  tabButtonText: {
    fontSize: 11,
    color: '#666',
    fontWeight: '500',
  },
  tabButtonTextActive: {
    color: '#fff',
    fontWeight: 'bold',
  },
  section: {
    padding: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 16,
  },
  subsectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 12,
    marginTop: 16,
  },
  loadingText: {
    textAlign: 'center',
    color: '#666',
    marginTop: 50,
    fontSize: 16,
  },
  // Cuadricula de tarjetas con numeros grandes (totales, promedios)
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  statCard: {
    width: '48%',
    alignItems: 'center',
    padding: 16,
    marginBottom: 8,
  },
  statNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: Colors.primary,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#666',
    textAlign: 'center',
  },
  rolesSection: {
    marginTop: 16,
  },
  rolItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  rolNombre: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
  },
  itemCard: {
    marginBottom: 12,
    padding: 16,
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  itemTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    flex: 1,
    marginRight: 8,
  },
  itemSubTitle: {
    fontSize: 14,
    color: '#666',
    marginBottom: 8,
  },
  itemDescription: {
    fontSize: 13,
    color: '#555',
    marginBottom: 8,
    fontStyle: 'italic',
  },
  itemMeta: {
    gap: 4,
  },
  itemMetaText: {
    fontSize: 12,
    color: '#666',
  },
  itemDate: {
    fontSize: 11,
    color: '#999',
    marginTop: 8,
    fontStyle: 'italic',
  },
  resultsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primary,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginTop: 10,
    gap: 6,
  },
  resultsButtonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
  },
  lastQuiz: {
    fontSize: 12,
    color: Colors.primary,
    marginTop: 8,
    fontStyle: 'italic',
  },
  noDataText: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
    fontStyle: 'italic',
    padding: 20,
  },
  // Panel compacto de filtros con buscador y desplegables
  filtroCardCompact: {
    padding: 12,
    marginBottom: 16,
  },
  searchInputCompact: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
    backgroundColor: '#fff',
    marginBottom: 12,
  },
  dropdownsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  dropdownSelector: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    backgroundColor: '#fff',
    padding: 8,
  },
  dropdownLabel: {
    fontSize: 11,
    color: '#999',
    fontWeight: '500',
    marginBottom: 4,
  },
  dropdownValue: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dropdownText: {
    fontSize: 13,
    color: '#333',
    fontWeight: '500',
  },
  dropdownArrow: {
    fontSize: 10,
    color: '#999',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  dropdownModal: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    width: '100%',
    maxWidth: 320,
  },
  dropdownModalTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 12,
    textAlign: 'center',
  },
  modalOption: {
    padding: 12,
    borderRadius: 8,
    marginBottom: 4,
    backgroundColor: '#f5f5f5',
  },
  modalOptionActive: {
    backgroundColor: Colors.primary,
  },
  modalOptionText: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
    textAlign: 'center',
  },
  modalOptionTextActive: {
    color: '#fff',
    fontWeight: 'bold',
  },
  fechaFiltros: {
    flexDirection: 'row',
    gap: 12,
  },
  fechaInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    backgroundColor: '#fff',
  },
  sectionHeader: {
    flexDirection: 'column',
    marginBottom: 12,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  resultCount: {
    fontSize: 14,
    color: '#666',
    fontWeight: '500',
  },
  pdfButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  pdfButton: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 8,
    opacity: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pdfButtonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  emptyCard: {
    padding: 32,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 16,
    color: '#999',
    textAlign: 'center',
  },
  verDetalleButton: {
    backgroundColor: '#007AFF',
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
    alignItems: 'center',
  },
  verDetalleButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  quizDetalleModalContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  quizDetalleModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  quizDetalleModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  quizDetalleModalCloseButton: {
    fontSize: 28,
    color: '#666',
    paddingHorizontal: 8,
  },
  quizDetalleModalContent: {
    flex: 1,
    padding: 16,
  },
  quizInfoSection: {
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
  },
  quizInfoTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 8,
  },
  quizInfoSubtitle: {
    fontSize: 14,
    color: '#666',
    marginBottom: 8,
  },
  quizInfoText: {
    fontSize: 14,
    color: '#333',
    marginBottom: 4,
  },
  statsSection: {
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
  },
  statsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 8,
  },
  statsText: {
    fontSize: 14,
    color: '#333',
    marginBottom: 4,
  },
  filtrosSection: {
    marginBottom: 16,
  },
  filtrosTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 8,
  },
  filtrosButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  filtroButton: {
    backgroundColor: '#e0e0e0',
    borderRadius: 8,
    padding: 8,
    flex: 1,
    alignItems: 'center',
  },
  filtroButtonActive: {
    backgroundColor: '#007AFF',
  },
  filtroButtonText: {
    fontSize: 12,
    color: '#333',
  },
  filtroButtonTextActive: {
    color: '#fff',
  },
  resultadosSection: {
    marginBottom: 16,
  },
  resultadosTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 8,
  },
  resultadoItem: {
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  resultadoNombre: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 4,
  },
  resultadoNota: {
    fontSize: 14,
    color: '#007AFF',
    marginBottom: 2,
  },
  resultadoRepeticiones: {
    fontSize: 12,
    color: '#666',
    marginBottom: 2,
  },
  resultadoFecha: {
    fontSize: 12,
    color: '#666',
    marginBottom: 2,
  },
  resultadoMateria: {
    fontSize: 12,
    color: '#666',
  },
  subSection: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  subSectionTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 8,
  },
  subItem: {
    marginBottom: 8,
    paddingLeft: 8,
  },
  subItemText: {
    fontSize: 12,
    color: '#333',
    marginBottom: 2,
  },
  subItemDate: {
    fontSize: 11,
    color: '#666',
    marginBottom: 2,
  },
  subItemMeta: {
    fontSize: 11,
    color: '#999',
  },
  sesionCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  sesionCardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1e293b',
    flex: 1,
  },
  sesionCodigoBadge: {
    backgroundColor: '#f1f5f9',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  sesionCodigoText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#475569',
    fontFamily: 'monospace',
  },
  sesionCardMeta: {
    marginTop: 4,
  },
  sesionCardMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 3,
  },
  sesionCardMetaText: {
    fontSize: 13,
    color: '#475569',
    marginLeft: 6,
  },
  sesionCardTopRanking: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
    gap: 6,
  },
  sesionTopBadge: {
    backgroundColor: '#f0fdf4',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  sesionTopText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#15803d',
  },
  sesionExpandButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    paddingVertical: 6,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  sesionExpandText: {
    fontSize: 12,
    color: '#6366f1',
    fontWeight: '600',
    marginRight: 4,
  },
  // Linea de tiempo visual con puntos conectados
  timelineContainer: {
    marginTop: 12,
    paddingLeft: 16,
  },
  timelineEvent: {
    flexDirection: 'row',
    marginBottom: 10,
    position: 'relative',
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginTop: 4,
    marginRight: 12,
    zIndex: 1,
  },
  timelineLine: {
    position: 'absolute',
    left: 4,
    top: 14,
    bottom: -10,
    width: 2,
    backgroundColor: '#e2e8f0',
  },
  timelineContent: {
    flex: 1,
  },
  timelineLabel: {
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 2,
  },
  timelineUsuario: {
    fontSize: 12,
    color: '#475569',
  },
  timelineFecha: {
    fontSize: 11,
    color: '#94a3b8',
    marginTop: 1,
  },
  timelineNota: {
    fontSize: 12,
    color: '#6366f1',
    fontWeight: '600',
    marginTop: 2,
  },
  rankingHeader: {
    flexDirection: 'row',
    backgroundColor: '#f8fafc',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  rankingHeaderText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748b',
  },
  rankingRow: {
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    alignItems: 'center',
  },
  rankingPosition: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  rankingPositionText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#fff',
  },
  rankingName: {
    flex: 1,
    fontSize: 13,
    color: '#1e293b',
    fontWeight: '500',
  },
  rankingNota: {
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 8,
    minWidth: 50,
    textAlign: 'right',
  },
  rankingTiempo: {
    fontSize: 12,
    color: '#94a3b8',
    marginLeft: 8,
    minWidth: 50,
    textAlign: 'right',
  },
  // Modal de detalle con informacion estructurada
  detalleModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  detalleModalContent: {
    backgroundColor: '#fff',
    borderRadius: 16,
    width: '100%',
    maxHeight: '90%',
    overflow: 'hidden',
  },
  detalleModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  detalleModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1e293b',
    flex: 1,
  },
  detalleModalClose: {
    padding: 4,
  },
  detalleModalBody: {
    padding: 16,
  },
  detalleSection: {
    marginBottom: 16,
  },
  detalleSectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#64748b',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  detalleInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  detalleInfoLabel: {
    fontSize: 13,
    color: '#94a3b8',
    width: 100,
  },
  detalleInfoValue: {
    fontSize: 13,
    color: '#1e293b',
    fontWeight: '500',
    flex: 1,
  },
  detalleModalFooter: {
    flexDirection: 'row',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    gap: 8,
  },
  detalleFooterButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 8,
    gap: 6,
  },
  detalleFooterButtonText: {
    fontSize: 13,
    fontWeight: '600',
  },
  sesionesEmptyContainer: {
    alignItems: 'center',
    padding: 40,
  },
  sesionesEmptyText: {
    fontSize: 14,
    color: '#94a3b8',
    textAlign: 'center',
    marginTop: 12,
  },
});

// Evitar que expo-router trate a este archivo como ruta
export default null;
